### ISSUE TITLE
Where is the UI?

### ISSUE THREAD

**Issue by justinkazemi** [cmoirano/secret-santa-generator#1]
I'm very interested in a secret santa application, but there appears to be no UI for this application. I want my Grandma to use this for next Christmas, and was hoping a new secret-santa-generator release could maybe help me achieve that dream. I believe this might help in case you need reference. http://en.wikipedia.org/wiki/User_interface

**Comment by cmoirano** [comment]
@justinkazemi similar to how there is no UI for a library in a programming language, this app is meant to be used as a tool for performance list sorting (e.g. speed and accuracy). The UI  is left to the discretion of the person who uses this.
